FROM triumfmlutils/baseml:v0.2

RUN wget 'http://www.muonsinternal.com/muons3/G4beamlineDownload.php?download&wfedorko@triumf.ca&G4beamline-3.06-Ubuntu64.tgz' && tar -xvzf G4beamlineDownload.php\?download\&wfedorko@triumf.ca\&G4beamline-3.06-Ubuntu64.tgz

RUN apt-get install -y x11-apps

RUN source G4beamline-3.06/bin/g4bl-setup.sh

